services:
  db:
    image: postgres:17
    #container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

volumes:
  data: