// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../service/mocks/mock_loyalty.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ioncode/gofermart/internal/domain"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockLoyaltyService is a mock of LoyaltyService interface.
type MockLoyaltyService struct {
	ctrl     *gomock.Controller
	recorder *MockLoyaltyServiceMockRecorder
	isgomock struct{}
}

// MockLoyaltyServiceMockRecorder is the mock recorder for MockLoyaltyService.
type MockLoyaltyServiceMockRecorder struct {
	mock *MockLoyaltyService
}

// NewMockLoyaltyService creates a new mock instance.
func NewMockLoyaltyService(ctrl *gomock.Controller) *MockLoyaltyService {
	mock := &MockLoyaltyService{ctrl: ctrl}
	mock.recorder = &MockLoyaltyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoyaltyService) EXPECT() *MockLoyaltyServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockLoyaltyService) Authenticate(ctx context.Context, login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockLoyaltyServiceMockRecorder) Authenticate(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockLoyaltyService)(nil).Authenticate), ctx, login, password)
}

// GetBalance mocks base method.
func (m *MockLoyaltyService) GetBalance(ctx context.Context, userID string) (decimal.Decimal, decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(decimal.Decimal)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLoyaltyServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLoyaltyService)(nil).GetBalance), ctx, userID)
}

// GetOrders mocks base method.
func (m *MockLoyaltyService) GetOrders(ctx context.Context, userID string) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockLoyaltyServiceMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockLoyaltyService)(nil).GetOrders), ctx, userID)
}

// GetWithdrawals mocks base method.
func (m *MockLoyaltyService) GetWithdrawals(ctx context.Context, userID string) ([]domain.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]domain.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockLoyaltyServiceMockRecorder) GetWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockLoyaltyService)(nil).GetWithdrawals), ctx, userID)
}

// Register mocks base method.
func (m *MockLoyaltyService) Register(ctx context.Context, login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockLoyaltyServiceMockRecorder) Register(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockLoyaltyService)(nil).Register), ctx, login, password)
}

// TokenTTL mocks base method.
func (m *MockLoyaltyService) TokenTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TokenTTL indicates an expected call of TokenTTL.
func (mr *MockLoyaltyServiceMockRecorder) TokenTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenTTL", reflect.TypeOf((*MockLoyaltyService)(nil).TokenTTL))
}

// UploadOrder mocks base method.
func (m *MockLoyaltyService) UploadOrder(ctx context.Context, userID, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOrder", ctx, userID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadOrder indicates an expected call of UploadOrder.
func (mr *MockLoyaltyServiceMockRecorder) UploadOrder(ctx, userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOrder", reflect.TypeOf((*MockLoyaltyService)(nil).UploadOrder), ctx, userID, orderID)
}

// ValidateToken mocks base method.
func (m *MockLoyaltyService) ValidateToken(ctx context.Context, tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockLoyaltyServiceMockRecorder) ValidateToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockLoyaltyService)(nil).ValidateToken), ctx, tokenString)
}

// Withdraw mocks base method.
func (m *MockLoyaltyService) Withdraw(ctx context.Context, userID, orderID string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockLoyaltyServiceMockRecorder) Withdraw(ctx, userID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockLoyaltyService)(nil).Withdraw), ctx, userID, orderID, amount)
}
