// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServerHandler creates a new instance of MockServerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockServerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockServerHandler is an autogenerated mock type for the ServerHandler type
type MockServerHandler struct {
	mock.Mock
}

type MockServerHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerHandler) EXPECT() *MockServerHandler_Expecter {
	return &MockServerHandler_Expecter{mock: &_m.Mock}
}

// AuthMiddleware provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) AuthMiddleware(next http.Handler) http.Handler {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for AuthMiddleware")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockServerHandler_AuthMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthMiddleware'
type MockServerHandler_AuthMiddleware_Call struct {
	*mock.Call
}

// AuthMiddleware is a helper method to define mock.On call
//   - next http.Handler
func (_e *MockServerHandler_Expecter) AuthMiddleware(next any) *MockServerHandler_AuthMiddleware_Call {
	return &MockServerHandler_AuthMiddleware_Call{Call: _e.mock.On("AuthMiddleware", next)}
}

func (_c *MockServerHandler_AuthMiddleware_Call) Run(run func(next http.Handler)) *MockServerHandler_AuthMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerHandler_AuthMiddleware_Call) Return(handler http.Handler) *MockServerHandler_AuthMiddleware_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockServerHandler_AuthMiddleware_Call) RunAndReturn(run func(next http.Handler) http.Handler) *MockServerHandler_AuthMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) GetBalance(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockServerHandler_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) GetBalance(w any, r any) *MockServerHandler_GetBalance_Call {
	return &MockServerHandler_GetBalance_Call{Call: _e.mock.On("GetBalance", w, r)}
}

func (_c *MockServerHandler_GetBalance_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_GetBalance_Call) Return() *MockServerHandler_GetBalance_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_GetBalance_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetBalance_Call {
	_c.Run(run)
	return _c
}

// GetOrders provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) GetOrders(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockServerHandler_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) GetOrders(w any, r any) *MockServerHandler_GetOrders_Call {
	return &MockServerHandler_GetOrders_Call{Call: _e.mock.On("GetOrders", w, r)}
}

func (_c *MockServerHandler_GetOrders_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_GetOrders_Call) Return() *MockServerHandler_GetOrders_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_GetOrders_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetOrders_Call {
	_c.Run(run)
	return _c
}

// GetWithdrawals provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) GetWithdrawals(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockServerHandler_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) GetWithdrawals(w any, r any) *MockServerHandler_GetWithdrawals_Call {
	return &MockServerHandler_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", w, r)}
}

func (_c *MockServerHandler_GetWithdrawals_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_GetWithdrawals_Call) Return() *MockServerHandler_GetWithdrawals_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_GetWithdrawals_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_GetWithdrawals_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) Login(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockServerHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) Login(w any, r any) *MockServerHandler_Login_Call {
	return &MockServerHandler_Login_Call{Call: _e.mock.On("Login", w, r)}
}

func (_c *MockServerHandler_Login_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_Login_Call) Return() *MockServerHandler_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_Login_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Login_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) Register(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockServerHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) Register(w any, r any) *MockServerHandler_Register_Call {
	return &MockServerHandler_Register_Call{Call: _e.mock.On("Register", w, r)}
}

func (_c *MockServerHandler_Register_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_Register_Call) Return() *MockServerHandler_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_Register_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Register_Call {
	_c.Run(run)
	return _c
}

// UploadOrder provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) UploadOrder(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_UploadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOrder'
type MockServerHandler_UploadOrder_Call struct {
	*mock.Call
}

// UploadOrder is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) UploadOrder(w any, r any) *MockServerHandler_UploadOrder_Call {
	return &MockServerHandler_UploadOrder_Call{Call: _e.mock.On("UploadOrder", w, r)}
}

func (_c *MockServerHandler_UploadOrder_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_UploadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_UploadOrder_Call) Return() *MockServerHandler_UploadOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_UploadOrder_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_UploadOrder_Call {
	_c.Run(run)
	return _c
}

// Withdraw provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) Withdraw(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockServerHandler_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockServerHandler_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockServerHandler_Expecter) Withdraw(w any, r any) *MockServerHandler_Withdraw_Call {
	return &MockServerHandler_Withdraw_Call{Call: _e.mock.On("Withdraw", w, r)}
}

func (_c *MockServerHandler_Withdraw_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerHandler_Withdraw_Call) Return() *MockServerHandler_Withdraw_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_Withdraw_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockServerHandler_Withdraw_Call {
	_c.Run(run)
	return _c
}
